pipeline {
    agent any
    environment {
        DOCKER_HUB_REPO = 'library_inventory'  // Replace with your Docker Hub repository name
        DOCKER_IMAGE = 'flask-app'
        DOCKER_CREDENTIALS_ID = 'dockerhub-credentials' // Replace with the ID of the Docker Hub credentials you created
    }
    stages {
        stage('Build') {
            steps {
                script {
                    echo 'Building Docker Image...'
                    // Debug: Print environment variables
                    echo "DOCKER_HUB_REPO: ${env.DOCKER_HUB_REPO}"
                    echo "DOCKER_IMAGE: ${env.DOCKER_IMAGE}"
                    
                    // Build the Docker image specifying the Dockerfile path
                    bat "docker build -t ${DOCKER_HUB_REPO}/${DOCKER_IMAGE} -f library_inventory/Dockerfile ."
                }
            }
        }
        /*
        stage('Test') {
            steps {
                script {
                    echo 'Running Tests...'
                    // Run tests using the Docker image
                    bat "docker run --rm ${DOCKER_HUB_REPO}/${DOCKER_IMAGE} pytest"
                }
            }
        }
        */
        stage('Deploy') {
            steps {
                script {
                    echo 'Pushing Docker Image to Docker Hub...'
                    // Log in to Docker Hub
                    withDockerRegistry([credentialsId: "${DOCKER_CREDENTIALS_ID}", url: 'https://index.docker.io/v1/']) {
                        // Debug: Print Docker login info
                        echo "Logging in to Docker Hub with credentials ID: ${DOCKER_CREDENTIALS_ID}"
                        
                        // Push the Docker image to Docker Hub
                        bat "docker push ${DOCKER_HUB_REPO}/${DOCKER_IMAGE}"
                    }
                }
            }
        }
    }
}
